### ISSUE TITLE
Refactor Code

### ISSUE THREAD

**Issue by adrianammt** [adrianammt/interval-timer#15]
## Value Statement
As a developer I want to have a clean code that is easy to maintain so I can come back in the future and make improvements easily.

## Acceptance Criteria
- [ ] Make the Form a reusable component

## Tasks
- [ ] Make the Form a reusable component
- [ ] Change from global state to reuse the state on every component from localStorage using a custom hook
- [ ] Create service functions for repeated functions
- [ ] Show update Setting in a different page
- [ ] Prevent sounds on re-rendering the form in the update page

## Complexity
Large
