### ISSUE TITLE
Create a card component in Storybook

### ISSUE THREAD

**Issue by adrianammt** [adrianammt/interval-timer#17]
## Value Statement
As a developer I want to be able to work on isolated components until I like the final design and can test the user experience.

## Acceptance Criteria
- [ ] Stories are displayed in StoryBook
- [ ] Stories have user functionality

## Tasks
- [ ] Create a story for the PlayClassCard, SavedClasses and NoClasses components
- [ ] Stories must be interactive when possible

## Complexity
Medium
