### ISSUE TITLE
Setup Basic Layout

### ISSUE THREAD

**Issue by adrianammt** [adrianammt/interval-timer#2]
## Value Statement
As a user of interval timer
I want to be able to easily understand the navigation flow, navigate through the options and use the app in my phone and tablet, so I can easily meditate or workout wherever I am.

## Acceptance Criteria
- [x] Responsive for all mobile devices
- [x] Header displays title according to the page it is at
- [x] The navigation between pages should work

## Tasks
- [x]  Define routes /create, /saved, /favorites
- [ ]  Make the / route redirect to /saved
- [x] Make the header and content change depending on location
- [x] Create basic components for 
        - [ ] Navigation (Footer)
        - [ ] Header
        - [ ] Main
- [x] Create Pages:
        - [ ] Create Page
        - [ ] MyList Page
        - [ ] Favorites Page
- [x]  Basic CSS Layout

## Complexity
Small
