### ISSUE TITLE
Setup Storybook

### ISSUE THREAD

**Issue by adrianammt** [adrianammt/interval-timer#20]
## Value Statement
As a developer I want to be able to use Storybook to create isolated components.

## Acceptance Criteria
- [ ] All Storybook files are displayed in my project
- [ ] npm run opens Storybook

## Tasks
- [ ] Install and prepare so I can start creating my card component.

## Complexity
Small
