### ISSUE TITLE
Message: User feedback when saved

### ISSUE THREAD

**Issue by adrianammt** [adrianammt/interval-timer#23]
## Value Statement
As a user of interval-timer I want to be sure that my class has been saved.

## Acceptance Criteria
- [ ] Shows toast message when saved
- [ ] Message is shown in all devices

## Tasks
- [ ] Install react-toast
- [ ] Import to Main, adjust time and position
- [ ] Create a component to customize toast
- [ ] Import component to Form

## Complexity
Small
