### ISSUE TITLE
Class Settings: Add sound preview on select

### ISSUE THREAD

**Issue by adrianammt** [adrianammt/interval-timer#27]
## Value Statement
As a user of interval timer, I want to be able to listen to the different sounds before choosing them.

## Acceptance Criteria

- [x] Each select option plays sound
- [x] Sound stops when the user clicks outside select

## Tasks
- [x] useState and useEffect for different sound types
- [x] control the play and pause of sounds

## Complexity
Medium
