### ISSUE TITLE
Saved classes: Edit option

### ISSUE THREAD

**Issue by adrianammt** [adrianammt/interval-timer#28]
## Value Statement
As a user of interval timer, I want to be able to edit my saved classes so I can fix duration or sounds.

## Acceptance Criteria
- [ ] When class card to play is showing, an edit element allows for edition
- [ ] Edit element opens preset values in the form
- [ ] Class is updated with same id in the localStorage

## Tasks
- [ ] Add edit icon
- [ ] Define when a class isEdit
- [ ] Add isEditToggle to set class isEdit to fals once Edit is completed
- [ ] Find class to edit and get the values inside the form
- [ ] Turn data in seconds back to a string for display
- [ ] On update set the class back into localStorage

## Complexity
Large
