### ISSUE TITLE
Create a Confirmation on Delete component

### ISSUE THREAD

**Issue by adrianammt** [adrianammt/interval-timer#39]
## Value Statement
As a user of interval timer, I want to be made aware of delete in case I clicked by accident.

## Acceptance Criteria
- [ ] Box must be hidden
- [ ] Box must show on click delete
- [ ] If user clicks No the class stays, if user clicks yes the class is removed
- [ ] Toast Message when class is removed

## Tasks
- [ ] Create a Component with initial view hidden
- [ ] Buttons in the component control onClick delete
- [ ] Pass component to CardComponent
- [ ] Fix delete button in CardComponent to display box instead of deleting

## Complexity
Small
