### ISSUE TITLE
Setup Deployment

### ISSUE THREAD

**Issue by adrianammt** [adrianammt/interval-timer#4]
## Value Statement
As a developer and contributor to this project
I want to see every increment deployed so its easy to test.
## Acceptance Criteria
- [x] main branch should be deployed after every change.
- [x] Every PR should have a corresponding deployment so it's easy for reviewers to check

## Tasks
- [x] Connect Vercel to this repository
Double check it shows:       
- [x]  Deployments for main branch
- [x]  Deployments for every PR

## Complexity
Small
