### ISSUE TITLE
Refresh styling

### ISSUE THREAD

**Issue by adrianammt** [adrianammt/interval-timer#42]
## Value Statement
As a developer I want to implement a design that makes the UX more agreeable. 

## Acceptance Criteria
- [x] No unnecessary code in css
- [x] Consistency in fonts, colors, shapes
- [x] New bg

## Tasks
- [x] Check if there are unnecessary lines of css
- [x] Review all elements and fix inconsistencies
- [x] upload and use new bg

## Complexity
Small
