### ISSUE TITLE
Create Welcome Page

### ISSUE THREAD

**Issue by adrianammt** [adrianammt/interval-timer#46]
## Value Statement
As a user of interval timer I want to see a first view of the app, so I know it is loading.
## Description
This feature imitates the functioning of a splash screen.

## Acceptance Criteria
- [x] Welcome page renders first and redirects to myList

## Tasks
- [x] Create a new page that holds the bg, logo and welcome message
- [x] Create a route for this new page and set it as home, redirect to it.

## Complexity
Small
