### ISSUE TITLE
Create page: Create a class (MVP)

### ISSUE THREAD

**Issue by adrianammt** [adrianammt/interval-timer#5]
## Value Statement
As a user of interval timer I want to be able to create and save a basic (1 Phase) class structure, so I can use it afterwards whenever I want.

## Acceptance Criteria
- [x] Time input must be visible in all browsers.
- [x] Must be clear for user which input is being selected
- [x] All options must have a predetermined / prefilled selection 

## Tasks
- [x] Create a Colors.css
- [x] Resolve how to showcase time picker (time input, text, external component)
- [x] Save class to local storage with sec input as number

## Complexity
Medium
