### ISSUE TITLE
Render component: No saved class message

### ISSUE THREAD

**Issue by adrianammt** [adrianammt/interval-timer#6]
## Value Statement
As a user of interval timer I want to know exactly what is expected of me, so I can start using the app.

## Acceptance Criteria
- [x] The only working icon should be the Create Class icon
- [x] The icon must open the create page
- [x] It is a conditional rendering, appears only if there is nothing saved in local storage

## Tasks
- [x] The + icon should link to the Create page

## Complexity
Small
