### ISSUE TITLE
Create page: Saved classes

### ISSUE THREAD

**Issue by adrianammt** [adrianammt/interval-timer#8]
## Value Statement
As a user of interval timer I want to be able to see all my saved classes so I can choose which one to play.
## Acceptance Criteria

- [ ] All saved classes must appear on the Saved Classes Page
- [ ] Each class has its own card showing name, duration, interval time

## Tasks

- [ ] Get data from local storage and map through each class to get name, duration and interval time.
- [ ] Create a Card Component and display it in the Saved Classes Page

## Complexity
Medium
