### ISSUE TITLE
Create page: Favorite classes

### ISSUE THREAD

**Issue by adrianammt** [adrianammt/interval-timer#9]
## Value Statement
As a user of interval timer, I want to be able to define which classes are my favourites for easy access.
## Description
Toggle Favourite icon must be present in all classCards. User can set/unset favourite from all views. Favourite view can also play the class.

## Acceptance Criteria
- [x] Toggle option works in all views
- [x] If no favourites are saved a message to invite to save fovourites appear
- [x] Class can be played from favourite view

## Tasks
- [x] Filter, map and display isFavourite in the Favourite page
- [x] Conditional rendering of message if no class is Favourite
- [x] Class can be deleted and played from favourite view

## Complexity
Medium
